project_id = "upscuqkxjvhzcriwljjl"

[functions.dify-chat]
verify_jwt = false

[functions.openai-embed]
verify_jwt = false

[functions.openai-chat]
verify_jwt = false

[functions.pdf-ingest]
verify_jwt = false

[functions.gdocs-sync]
verify_jwt = false

[functions.notion-sync]
verify_jwt = false
 
 [functions.gdrive-sync]
 verify_jwt = false